### ISSUE TITLE
Permission errors when testing in a Docker container

### ISSUE THREAD

**Issue by mjbryant** [uber/pyflame#18]
I tried to build and test this entirely in a Docker container and got permission errors. I'll try to be as explicit as possible so this is reproducible. Please let me know if I'm just doing something silly.

This is running on a Lucid machine, using the Trusty base image.

## General approach

I'm running the Docker image from the Dockerfile below then attaching to the container with a new bash shell (`docker exec -i -t <container> /bin/bash`) and running `pyflame <test_script.py's PID>`. I always get the permission error message `Failed to attach to PID <PID>: Operation not permitted`.

`test_script.py` is just a trivial python script I was using to test.

## Dockerfile
```
FROM ubuntu:trusty

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y dist-upgrade
RUN apt-get install -y \
    autoconf \
    autotools-dev \
    cmake \
    bash \
    git \
    g++ \
    pkg-config \
    python-dev

RUN mkdir -p work
WORKDIR work

ADD test_script.py /work/test_script.py
ADD test_file /work/test_file

RUN git clone https://github.com/uber/pyflame.git
RUN cd pyflame && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install

USER nobody
CMD python test_script.py
```

## Things I've already tried

- I've confirmed that `kernel.yama.ptrace_scope = 0`
- I've run the container as root and attached and ran pyflame as root

**Comment by jeevandev** [comment]
The setup we have is pyflame runs on the host with appropriate permissions. It attaches to the specified docker instance on that host & does profiling on that using ptrace. @eklitzke Any idea about the issue?

**Comment by eklitzke** [comment]
Are you using the PID from inside the container, or outside the container? If you're running Pyflame from the host you need the outside PID.

**Comment by mjbryant** [comment]
I am attempting to run Pyflame from inside the container, and using the inside-container PID.

**Comment by eklitzke** [comment]
We normally run pyflame from outside the container, since it's easier for us to deploy that way. That said, what you're trying to do should work. I'll probably get a chance to look into this later this week.

Thanks for the detailed bug report!

**Comment by eklitzke** [comment]
Hi Michael,

The issue is that by default Docker images don't have the `SYS_PTRACE` capability. If you try to use `strace` or `gdb` within a Docker container you'll get the same problem. I found a good article describing the issue, as well as how to enable ptrace, here: http://blog.johngoulah.com/2016/03/running-strace-in-docker/

If you are able to strace other processes within a container, but are not able to run Pyflame, then please re-open this and let me know.

In a future release I will try to add code to Pyflame to detect when `yama.ptrace_scope` is too restrictive, or when the process does not have the `SYS_PTRACE` capability so that a better error message can be printed to the console.

Cheers, and tell msolo I say hi :-D.
