### ISSUE TITLE
Failed to PTRACE_PEEKDATA at 0x6664ba09e8: Input/output error

### ISSUE THREAD

**Issue by fcxjluo** [uber/pyflame#71]
I installed pyflame in the Centos6.5(with python2.6).When I execed `pyflame {$pid}`,it shown this info.I don't know why,please help me,thanks.

**Comment by jeevandev** [comment]
Did you check the ptrace issues listed in FAQ?

**Comment by eklitzke** [comment]
I tried to reproduce this, but I couldn't get Pyflame to build on Centos 6.5 (installed in a VM). The issue is that even after hacking up `configure.ac`, the code won't compile under GCC 4.4. If you can provide me with a reproducible failure environment I will consider reopening this.

Note that Pyflame *does* support Python 2.6, since the tests run against that already.

**Comment by faicker** [comment]
@eklitzke 
I didn't meet this problem on centos6.
I can provide the install instructions on centos6 as follows,
1. install dep of higher version gcc and autotools,
`
yum install centos-release-scl
yum install devtoolset-3-gcc devtoolset-3-gcc-c++
rpm -ivh https://www.softwarecollections.org/en/scls/praiskup/autotools/epel-6-x86_64/download/praiskup-autotools-epel-6-x86_64.noarch.rpm
yum install autotools-latest
yum install python-devel
`
2. make a python2.pc file, ` /usr/lib64/pkgconfig/python2.pc`
`
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include
Name: Python
Description: Python library
Requires:
Version: 2.6
Libs.private: -lpthread -ldl  -lutil
Libs: -L${libdir} -lpython2.6
Cflags: -I${includedir}/python2.6
`
3. compiling,
`
    scl enable devtoolset-3 bash
    scl enable autotools-latest bash
    ./autogen.sh
    ./configure
    make
`
